### ISSUE TITLE
[Enhancement] Configurable polling frequency

### ISSUE THREAD

**Issue by rcork** [explosivo22/kwikset-ha#47]
I've modified device.py to change the default update interval from 30 seconds to 5. Is there a reason why this can't be user configurable? I've changed mine to 5 as i have exposed the lock via Apple Homekit HA integration and found the 30s to be too long for some automations that i want triggered based on lock status.

**Comment by explosivo22** [comment]
I have it at 30 seconds just because I didn't want to be responsible for kwikset to get upset and start seeing too many queries considering this was a reverse  engineer of there stuff. I will look into making it configurable per user and maybe that won't upset them. If it does, then maybe just on a user by user basis.

**Comment by explosivo22** [comment]
I have not implemented this, but I don't see that HA allows this.  I believe they are removing the ability per [this](https://github.com/home-assistant/core/issues/83918) thread.  I know you can do this via an automation that can run every 5 seconds or whatever value is preferred.

```
alias: Update Every Second
description: ""
triggers:
  - seconds: /5
    trigger: time_pattern
conditions: []
actions:
  - data:
      entity_id:
        - switch.front_door_audio
        - switch.front_door_secure_screen
    action: homeassistant.update_entity
mode: single
```
